source/docs/quickstart.md
The current quickstart seems a bit confusing when it comes to the login part. At first glance it appears that the instructions for virt-manager are missing but in fact it just links to a blog (that might go away at some point) and proceeds to explain the process for VirtualBox.
I've added some information on how to generate the image - it's the same for both platforms, and also how to make sure your VM will pick it up in virt-manager.
=> Add virt-manager cloud-init to Quickstart

source/docs/quickstart.md
Helping troubleshoot an issue in IRC, it was noted by @larsks that copy and pasting from the website resulted in leading spaces in the text for the user-data and meta-data files.  This was causing issues with cloud-init not picking up the contents of the file.  The issue stemmed from using a code span indicator instead of indents to wrap the block.    As an aside, this is a Middleman render issue since github renders the original and this PR the same way, with no leading spaces.
For code blocks in lists, the indent becomes dependent on list sublevel, so the right indent for code block is 4 x the indent level.  So for this case, 8 spaces.  There were some ways to combine span indicators and indent, but I didn't find one that resulted in no leading spaces when copying from the site.
I also …
=> Updating quickstart to fix copy/paste issue with markdown rendering

source/docs/gettingstarted.md
Here's the first run at a new GSG for Project Atomic.  
This guide works from the new operating premise discussed on list and in IRC, mainly an Atomic cluster using the available tools.  I've started with an all Atomic premise, with one host selected as master.  The other idea here is to lean on other documentation instead of repeating content.  I've pointed to the Quick Start guide for launching hosts under a VM manager for example.  In the long run, there are other sections that could be moved to separate docs as well.
It currently has a kubelet service workaround until kubernetes-0.9.1 makes it into the tree (currently in testing for F20/21) which I'll remove later.  Otherwise, all commands are functional and result in a working cluster in all of my testing.  I've also ensured …
=> New Getting Started guide

source/docs/gettingstarted.md
Modified the flanneld key in etcd to a cluster unique name to be more friendly for people running an etcd cluster that could service multiple kubernetes clusters.
Also noticed that upstream kubernetes modified the guestbook examples that required some fixes to the way the publicly accessible guestbook service was created.  Also changed the syntax to reflect the appropriate kubernetes 0.9.1 syntax.
=> Change etcd key and updates to Guestbook example

source/docs/docker-storage-recommendation.md
There have been quite a few questions on the Ask site about extending storage  and the existing "Setting Up Storage" document references the default docker location.  This doc walks through using docker-storage-setup as a user, and talks some about the devicemapper backend and direct LVM pools.  It could be expanded greatly with more info about the backend and thin pools.
It may also not be the best way forward long term, this helper works but doesn't seem like it was intended for admin use so much as system use.  We can add a manual section as well, but I wanted to get something out that reflected the current state and hopefully stemmed a few more questions in the community.
=> Updated storage document for devicemapper thin pool

source/download/index.html.haml
Change k8s docs pointer to our new atomic-specific docs
=> add reference to k8s getting started docs on download page

source/docs/quickstart.md
Following in the foosteps of the storage doc, modifying the quickstart to use the helper tool to add the new device rather than the /var/lib/docker method.  This is a manual run of the tool, not on reboot.  I'm not removing the /etc/sysconfig file, which causes the script to fire on boot, but doesn't cause issues (so far).  If there's a consensus, I can add a final step to remove the file after verifying the additions.
=> Update quickstart to use docker-storage-setup

source/docs/index.html.haml
Split info about the document format and how to edit a document into two sentences.
=> typo: Fix run-on sentence in index.html.haml

Dockerfile
The Middleman build fails in this container with unresolved dependencies for the latest version of nokogiri.  Also the latest Fedora container doesn't pull in tar.
The missing dependencies are:
* tar
* libcurl-devel
* zlib-devel
* patch
=> Adding build requirements for nokogiri 1.6.6.2 to yum install stanza

source/blog/2015-05-20-building-and-running-live-atomic.html.md
A post about building live Atomic image, configuring it, booting it with PXE, and using iSCSI for docker images.
=> Pxetolive blogpost

source/stylesheets/_application-custom.css.sass
This ties the icons to the navigation items, instead of the navigation position.
=> changed navigation icons to use named classes, instead of nth-child()

source/download/index.html.haml
Updated to the new Atomic landing page for F22 Cloud release and the new bare metal ISO installer.
Added a note about the availability of Vagrant images.
Changed  reference of "rpm-ostree" to "atomic host".
Also minor reorder of entries for Fedora/CentOS hosts to make a bit clearer as to which distro was releasing what.  I removed the version from the Fedora button, make the buttons about the same size.
=> Updates for F22 release

source/docs/fedora_atomic_bare_metal_installation.md
Update for Fedora 22:
- We don't use extlinux
- The content is no longer in the squashfs, so you can't use file:// with PXE
=> docs/baremetal:

source/docs/fedora_atomic_bare_metal_installation.md
Noted boot.iso pointed to old RC candidate, `atomic host` changes needed.
@cgwalters proposed changes that slightly modifies the need to rebase the installed tree.  Didn't want to drop it completely but indicate it may not be needed.
Builds on but shouldn't conflict with #137
=> Update boot.iso and minor cleanup

source/blog/2015-06-30-creating-a-simple-bare-metal-atomic-host-cluster.html.md
The current default of http is insecure.
=> blog: Use https for repo URL

source/docs/nulecule.md
The links on the nulecule site call to the same dir (unless getting-started.md/implementation.md,etc is suppose to be on the main site?) rather than Github.
=> broken links on nulecule site

source/docs/quickstart.md, source/download/index.html.haml
I've talked to a few folks who didn't realize we had more than the quickstart guide.  The main confusion came from the layout of the page that is listed as "Getting Started" in the nav bar, but started life as the downloads page.  
I put a bigger emphasis on the GSG and the Quickstart guide as the entry points, and cleaned up some language.  I also removed the Extreme Quickstart, that was what some folks thought were "the official instructions".
I also reflowed the Quickstart guide to put more emphasis on the steps rather than the virtualization providers to eliminate duplication.
Thoughts?
=> Clarify documentation entry points and clean up quickstart

source/blog/2015-09-02-using-a-spc-to-troubleshoot-containers.html.md
This is a bit of a walk through on how / why you would create a super privileged container using sysdig as the example tool.  Highlights using a LABEL to simplify how an upstream container builds a normal docker run command line.
=> Blog post about creating / running a super privileged container

source/download/index.html.haml
Point to download page on centos wiki, point out that vagrant and iso images exist for centos, as well.
=> update download page to point at centos wiki

source/blog/2015-09-15-introducing-vendor-labels2.html.md
The Container Application Generic Labels
repository now has a vendor directory
for ISVs to document their metadata
requirements.
=> Blog post on vendor metadata repo

source/blog/2015-09-21-clustering-atomic-hosts-with-kubernetes-ansible-and-vagrant.html.md
Couple small fixes for this post, cite version of Fedora I tested with, point out need for upstream vagrant for f22/centos.
=> minor fixes in post

source/blog/2015-10-05-setting-up-skydns.html.md
Someone mentioned the first sentence was confusingly phrased (implying Kube doesn't have DNS today) so I've reworded it to make it clearer that the server must be run on top of the cluster.
=> Suggested changes to DNS lead sentence

source/blog/2015-10-09-updated-spc-sysdig-container.html.md
The Sysdig team released containers that support Atomic and the `atomic run` docker LABEL shortly after our original blog post.  This is a short new post talking about how to run the new SPC.
=> New post on Atomic enabled sysdig

source/docs/gettingstarted.md
Recent Kubernetes releases don't require the `--machines` flag for the controller manager. Instead, nodes self-register.
Reference: http://kubernetes.io/v1.0/docs/admin/node.html#self-registration-of-nodes
=> Remove KUBELET_ADDRESSES from Getting Started

source/docs/nulecule.md
To match the usage that the rest of these docs use.
=> source/docs/nulecule: Prefix 'Nulecule specification' with 'The'

source/blog/2015-11-18-atomic-app-0-2.html.md
A quick summary of our release of 0.2.1 as well as 0.2.2.
Our next release (0.3) will introduce a few more providers, so it'll be much bigger than this post :). Yay Mesos and Docker Compose!
=> Blog post of atomicapp 0.2

source/docs/usr-bin-atomic.md
Sinceall supported Fedora and Centos atomic build host support atomic,
no need to say this is Fedora 22 alpha.
=> Clarify where is atomic

source/community/index.html.haml
http://rpm-ostree.cloud.fedoraporject.org serves up the default apache page, I'm not sure what used to live there but should we remove these links?
=> Remove links to rpm-ostree.cloud.fedoraporject.org

source/docs/cockpit.md
* Add link to upstream documentation
* Add links to blog post about running as a service
I also removed the beta/preview language and link to the Fedora change for cockpit -- LMK if that's premature...
=> update cockpit doc page

source/docs/atomicapp.md
* Fix Nuleclue example URL in atomicapp.md in order to make the link exist (the older link produced a 404).
=> update: Fix Nuleclue example URL in atomicapp.md

source/blog.html.haml
While I agree we should make the feed link more visible, this adds the feed link to the head section of the blog index page. Individual articles had this already, but looks like it was missing from /blog/ itself. I guess some feed readers can pick it up from there.
Let's discuss the feed icon etc separately, that might be a good idea too.
=> announce feed in blog page's header

data/site.yml, source/layouts/_footer.haml
This might be handy for quick edits to get more contributions? It shows an "edit this on github" link for all pages except for the blog (where it kinda makes less sense)
I tried to think of any other pages where it wouldnt make sense but none occurred to me immediately.
=> add github edit link to page footer (except blog)

source/blog/2016-03-11-docker-credentials-store.html.md
Replaces PR from @runcom with one I've edited.  @runcom, @rhatdan, etc., please approve.
@bproffitt, once this is approved by them it's ready to go.
One query though:
"credentials store" vs. "credential store"?  Which?
=> Runcom docker credentials store

data/authors.yml, source/blog/2016-03-17-no-new-privs-docker.md
This is the revised version of @mrunalp 's post about no-new-privileges.  It is not ready to go yet.  There's a number of questions:
* @mrunalp, I had to revise the post significantly, please verify that I didn't add any errors
* @mrunalp it's your patch to Docker, no?  Shouldn't we credit you by name?  Who else worked on it?
* @rhatdan, @jlebon, @jasonbrooks please check sample code, thanks!
=> Added revised version of the no-new-privs post.

BUILD.md, Nulecule/artifacts/docker/atomic-site-run
issue #274 
Tomas, please try the updated instructions and docker-run command to see if it fixes the run for you.
@TomasTomecek
=> Made changes to Atomic App instructions, run command in response to

source/docs/atomicapp.md
This documentation is largely outdated and needs to be updated to
everything that's new in Atomic App.
For example, we no longer use `atomicapp build`.
=> Update Atomic App documentation

source/download/index.html.haml
This is a tricky balance but I think we should point people at more
production configurations first.  Fedora and CAHC should more be
development options.
=> download: Reorder to have CentOS first

source/blog/2016-07-27-download-and-get-involved-with-fedora-atomic-24.html.md, source/blog/2016-07-28-download-and-get-involved-with-fedora-atomic-24.html.md
This post should be timed to come out after the next fedora atomic two-week release, which should be today (July 26), is out and on the mirrors and updated in hashicorp atlas. The post includes info about:
* how to get fedora atomic 24, 
* how to upgrade an existing system, 
* how to test with the testing tree, and 
* which packages to look out for for testing.
=> post about fedora atomic 24

source/index.html.haml, source/stylesheets/_application-custom.css.sass
I was getting the annoying CSS warning as :
```
.....
WARNING on line 163 of /tmp/source/stylesheets/_application-custom.css.sass:
This selector doesn't have any properties and will not be rendered.
```
Please feel free to the discard PR if you think `#secondary` needs some content.
=> Fixed SASS warning

source/blog/2016-08-18-docker-patches.html.md, source/docs/docker_patches.md
This contains Dan's post on Docker patches, as well as a visually organized table of patches we maintain.
@rhatdan, questions:
1. Your blog post mentions backporting fixes, but none of the listed patches are of that type.
2. Is there a PR or Issue for Improved-searching-experience?
3. If you can build the site, please check out the new docker_patches doc I created to see if that works for you.
@bproffitt, I took one pass at editing this, but it's a LOT of text.  Please look for basic spelling/grammar issues I might have missed?
=> Added blog post and table of patches.

source/docs/gettingstarted.md
I kept it and it worked. There is no value from removing it.
If you believe otherwise, please at least tell us why we need to remove it.
=> Revert removing `ServiceAccount` from admission control

source/blog/2017-02-08-crio-runtimes.html.md
The embedded video wasn't loading for me using FF51.  The dev console
showed the following error:
`Load denied by X-Frame-Options:
https://www.youtube.com/watch?v=gEBSCesjkvA does not permit
cross-origin framing.`
After some hunting around via Google, I found that the URL of the
video had be tweaked slightly to avoid the issue.  Additionally, I
resized the iframe to fit within the body of the post.
=> blog:  fix CRI-O video embed

source/docs/atomic-host-networking.md, source/docs/kubernetes.md
The official kubernetes repository changed the links of the files markdown for a documentation page. The old links were all going to 404.
=> Pr fix 404 links

source/docs/kubernetes.md
This replaces the mostly-blank kubernetes page on the site w/ info about the state of kube on fedora atomic, centos atomic, and centos atomic continuous, and includes info about the state of containerized kube.
=> populate kubernetes page with host-specific info

source/docs/docker-image-author-guidance.md
The official docker page docs changed the links. The old links were all going to 404.
=> Fix links that are with 404

source/blog/2017-04-13-rpm-ostree-v2017.4-released.html.md
New blog post highlighting recent rpm-ostree features. I'd like to make this a regular thing, though since it's been a while, the post also includes features from the last few releases.
=> blog: rpm-ostree v2017.4 released

source/blog/2017-04-29-rpm-ostree-v2017.5-released.html.md
I dated this Apr 29th, to give the testing branch time to compose.
=> blog: rpm-ostree v2017.5 released

source/blog/2017-03-29-migrate-fedora-atomic-host-to-overlay2.md, source/blog/2017-05-04-migrate-fedora-atomic-host-to-overlay2.md
@cgwalters posted an informative message to the mailing list about
migrating to `overlay2` from `devicemapper`.  I thought it would be
good to put it on the blog for additional visibility.
=> blog: short post on switching to overlay2 driver

source/blog/2017-06-02-future-plans-for-fedora-atomic-release-life-cycle.html.md
There was a misunderstanding about this short-term stable ref idea, so let's strike this sentence.
=> strike reference to near-term stable ref

BUILD.md, Dockerfile, docker.sh
Add a `RUN` label and make `docker.sh` use `atomic run`. This makes it
easier for humans to rerun middleman without having to rebuild the
image everytime.
=> Dockerfile: use RUN label to make re-running easier

source/blog/2017-06-04-6-reasons-why-cri-o-is-the-best-runtime-for-kubernetes.html.md
@jberkus @rhatdan @bproffitt PTAL
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
=> Add "6 Reasons why CRI-O is the best runtime for Kubernetes" blog

source/blog/2017-06-22-introducing-buildah.html.md
The last bit of the diff below we used to say 
"container-building tools, since neither a server process nor root access are required."
However root access is required.  I've reworded this to: 
"container-building tools as a server process is not required.".
=> Remove invalid root access reference

source/blog/2017-07-14-unprivileged-containers-with-bwrap-oci-and-bubblewrap.md
The original bwrap-oci link gets incorrectly converted to
<https://www.projectatomic.io/blog/2017/07/unprivileged-containers-with-bwrap-oci-and-bubblewrap/git@github.com:.gitb>
=> fix bwrap-oci link

source/blog/2017-07-25-fedora-atomic-july-25.html.md
Fix references to fedora 25 and also update links to vagrant
cloud.
=> update 25th Atomic Host release post

data/authors.yml, source/docs/quickstart.md
I had a use case where I was trying out Atomic Host on a Fedora 26 server with no GUI.  I thought it would be useful to add the CLI-method for libvirt users to get started when virt-manager isn't an option.
=> Updated Quickstart Guide for CLI-only Method

source/docs/quickstart.md
This fixes the previous merge.  From what I can tell, the last merge that built the site wasn't formatting the new changes properly as code blocks (I assume in the Markdown to adoc conversion).  I just added an additional backtick in my CLI examples according to the working examples.
=> Fixed formatting issue with CLI examples.

source/docs/docker-image-author-guidance.md
Removed the `MAINTAINER` instruction as it is deprecated.
Replaced it with `LABEL maintainer`.
=> Replace the `MAINTAINER` instruction

source/docs/index.html.haml
=> Fix Link to Container Best Practices on Docs index

source/blog/2017-11-08-migrating-kubernetes-on-fedora-atomic-host-27.html.md, source/blog/2017-11-15-migrating-kubernetes-on-fedora-atomic-host-27.html.md
I have TK's in here for a link to the main upgrading f27 atomic post, and we need to get the system containers referenced in here built/released.
=> post on migrating kube on f27

config.rb
Since we are moving it out of openshift, we need to use another name
=> Use the new url for the tracker

source/blog/2018-02-06-fedora-atomic-workstation.html.md
Switch to download.fedoraproject.org, which will send people to the
mirrors.
=> switch to mirror url in FAW blog post

source/blog/2018-01-26-using-image-registries-with-buildah.md
Firefox show a warning regarding insecure content, since the blog post is
on the frontpage.
=> Do not hardcode http in url for image

data/authors.yml, source/blog/2018-03-06-the-many-ways-to-build-oci-images.md
This is an overview post that covers some of the ways users can build
OCI images without having Docker installed on their host.
=> blog: the many ways to build oci images without docker

data/authors.yml, source/blog/2018-03-06-update-kernel-arguments-on-atomic-host.html.md, source/blog/2018-03-08-update-kernel-arguments-on-atomic-host.html.md
This is my first attempt to try to submit a blog post to atomic site. So If there is anything I did wrong/horribly wrong(hopefully not the latter), feel free to point it out :). 
The blog was to introduce the `rpm-ostree ex kargs` command that was introduced a while ago. We discussed a bit about this in a standup, and it seemed to be a good option of having a blog post for ppl to test it out and give feedbacks.
That's why I am here :p. Comments are welcome and thanks in advance!
=> blog: update kernel arguments on Atomic Host

source/blog/2015-09-28-creating-custom-ostree-composes-for-atomic-testing.html.md
This blog post is still useful, but most of the links are broken.
Fix them to lead to the right information.
=> Update links on "Creating Custom ostree Composes for Atomic Testing"

source/blog/2018-03-20-new-rpm-ostree-features.html.md
It's been a while since the last rpm-ostree release blog post. This is a
summary of changes since then with more emphasis on rojig and automatic
updates.
I didn't really have time to go into too much details on the other new features,
though I included links to the relevant upstream discussions.
=> blog: latest rpm-ostree features

source/blog/2018-04-09-test-day-for-fedora-28-atomic-cloud-april-11th.html.md
Link for test page wiki and test cases are not yet available. Will update this PR with those links once they are available.
=> Add blog for Fedora 28 Atomic/Cloud Test Day

source/blog/2018-05-01-fedora-atomic-27-to-28-upgrade.md
I basically took @dustymabe's post for f26 -> f27 and updated it for
Fedora 28.
=> blog: upgrade from f27 -> f28

source/docs/gettingstarted.md
* Use master IP in `ETCD_ADVERTISE_CLIENT_URLS`. With `0.0.0.0`, `etcdctl` on Kubernetes nodes will try to connect to http://0.0.0.0 which won't work from a node.
* `/etc/kubernetes/apiserver`:
* `--address` is deprecated, replaced with `--insecure-bind-address`
* `--portal_net` is deprecated, replaced with `--service-cluster-ip-range`
* Enable and start `flanneld` on the master. Needed for accessing pods using flanneld IPs.
* `/etc/kubernetes/kublet`:
* Update `--hostname_override` to `--hostname-override`
* Update `--api_servers` to `--api-servers`
* Add `--cluster-cidr` to Kubernetes Proxy
* Set `iptables` `FORWARD` `ACCEPT` policy on the nodes
* Fix wording
=> Fix misisng setup setps and deprcated parameters

source/index.html.haml
Refer to Team Silverblue instead of Fedora Atomic Workstation,
and link to www.teamsilverblue.org.
=> Refer to Team Silverblue

data/authors.yml, source/blog/2018-06-06-building-kernel-modules-with-podman.md
This PR adds a blog post detailing out how to build a kernel module on Atomic inside a container with Podman.
=> Kernel modules with atomic and podman

data/docs.yml, source/docs/index.html.haml, source/docs/quickstart.md, source/download/index.html.haml
The Getting Started Guide for setting up an Atomic Cluster and the
docs around Kubernetes are old, unmaintained, and hard to provide
support for.
Let's stop pointing users at these docs and try to find a better way
for users to experiment with kubernetes, etc.
This is not an exhaustive removal of the links to both guides, but the
primary entrypoints that I found.
=> remove links to unsupported documentation

source/index.html.haml
The canonical URL for the Silverblue project appears to be https://silverblue.fedoraproject.org, not https://teamsilverblue.org/. While https://teamsilverblue.org/ looks to have redirected to the proper site in the past it currently does not. Also, the ownership of teamsilverblue.org is unclear (to me) but judging by the IP and name server it does not seem to be an official Fedora Project domain.
=> Modified Team Silverblue URL

source/docs/kubernetes.md
The current link repository has a [README](https://github.com/kubernetes/contrib/blame/master/ansible/README.md#L3) with this message:
> **DEPRECATED**: See repo https://github.com/kubernetes-incubator/kubespray
This pull request updates the link to the new repository.
=> docs: update link to upstream kubernetes ansible

source/docs/gettingstarted.md
I been walking through this guide today finding some areas where updates are needed.
Add a note pertaining to the installation of `etcd`. The rpm-ostree command should not be used if etcd has been installed already as a system container.
=> Add a note about the system container install of etcd

source/docs/quickstart.md
Without introducing the default user concept beforehand, the user-data file description feels incomplete.
=> Mention usernames earlier in the quick start guide
