- source/docs/quickstart.md
Report on IRC for old images in the Quickstart links.  Updated images section to refer to Download page,
> Quickstart

- source/docs/gettingstarted.md
Some changes are coming in variables for Kubernetes, mainly for this is KUBE_MASTER requiring a transport type.  Works in the current 0.11 shipped in the latest tree, still has old version for 0.9.1.
I also looked at the guide in the docs for Kubernetes, and made some changes to where values get set.  I want to make sure we set multi-service values (KUBE_MASTER, ETCD, etc) in config and service specific values in the service config.
I wanted to be more explicit about all the networking types so added more info about the networks up front, minor discussion of service addresses in kubelet config.
Fixed a few typos, and changed the publicIPs example to a list from a single value to show syntax.
Changes primarily spurred by comments in IRC on coming changes and questions between this PA guide …
> Some changes in values for k8s 0.11 / 0.12

- data/site.yml
- source/javascripts/lib/juvia.js
hosted from juvia instance used by community.redhat.com
> enable juvia comments

- source/docs/index.html.haml
This is a simple correction of an incorrect verb.
> s/it is build/it is built/g in index.html.haml

- source/docs/index.html.haml
I reworded the "Learning More" section on the docs main page.
This edit lightens the reader's cognitive load.
> Reworded the 'Learning More' text

- source/docs/index.html.haml
This edit changes the wording of a sentence to lower the cognitive load on the reader.
> improved the wording of the 'Getting Started' section

- source/blog/2015-05-26-atomic-app-0-1-0.html.md
As I cant push to atomic-site directly...
Thanks for the help!
> some minor edits

- source/blog/2015-05-27-atomic-app-0-1-0.html.md
> some additions

- source/docs/cockpit.md
- source/download/index.html.haml
Fix all info on how to use Cockpit in order to reflect the move from Cockpit as part of the Atomic system into a reflect privileged container
> Patch Cockpit usage

- source/docs/gettingstarted.md
Made some changes for etcd and kubernetes for the new Fedora 22 release, removed some of the kubernetes upgrade notes from Fedora 21.
Added a new sections with explicit information about the environment used in the guide and the end state.
Includes "atomic host" changes from #131
Also replaced the upstream kubernetes guestbook example with a simpler pod.  Now that we've posted an atomic-app / nulecule blog, I'd like to get the example changed to use those rather than "raw" kubernetes.
> Updated for Fedora 22, removed guestbook example to prep for nulecule

- source/blog/2015-05-26-building-and-running-live-atomic.html.md
> Fix formatting.

- source/docs/gettingstarted.md
Adding specific version from `atomic host status` to requirements matrix to ensure best compatibility and completeness
> Add Atomic version

- source/docs/nulecule.md
- source/nulecule/spec/0.0.2/index.md
> Nulecule additions

- source/blog/2015-07-21-follow-us-the-nulecule-has-moved.html.md
added a blog post about the new home of the spec  and the nulecule image spec ext
> added a blog post about the new home of the spec 

- source/docs/gettingstarted.md
I had to make those two changes to get kubernetes working on a Fedora Atomic host with all updates applied.
> Small changes to get kubernetes 1.0 running

- source/blog/2015-09-01-using-a-spc-to-troubleshoot-containers.html.md
I was contacted by Marcus @ Sysdig who let me know the URL to their homepage was broken.  Added the missing protocol to the link ref.
> Sysdig URL missing protocol

- setup.sh
```
Gem::Ext::BuildError: ERROR: Failed to build gem native extension.
/usr/bin/ruby -r ./siteconf20150909-305-doaab5.rb extconf.rb 
checking for clock_gettime() in -lrt... yes
creating Makefile
make "DESTDIR=" clean
sh: make: command not found
make "DESTDIR="
sh: make: command not found
make failed, exit code 127
```
and this went even further until I installed all required packages
> Setup: update dependencies

- .travis.yml
This help to see why the build fail, as seen with
https://github.com/projectatomic/atomic-site/pull/176
> Make travis be verbose by default

- source/blog/2015-09-08-introduce-atomic-reactor.html.md
> blog: introduce atomic-reactor

- source/blog/2015-09-15-combined-fedora-centos-atomic-test-day-next-week.html.md
announcing sept 22 fedora/centos atomic test day
> test day post

- source/docs/quickstart.md
There was still some confusion on the #cloud-config not
being a comment
> Add some emphasis to the Quickstart

- source/blog/2015-12-15-ADB-1-5.html.md
Signed-off-by: Lalatendu Mohanty <lmohanty@redhat.com>
> Addng a blog for Atomic developer bundle 1.5.0 release

- source/blog/2015-12-16-atomic-app-0-3.html.md
Adds the 0.3.0 release blog post
> Atomic App 0.3.0 release post

- data/authors.yml
- source/blog/2016-01-07-atomic-diff.html.md
Highlight the new atomic diff subfunction on projectatomic.
> atomic diff blog

- source/blog/2016-01-14-atomic-app-0-3-1.html.md
Still need to add:
Other than that, it's good to go. Will ping the respective people when it's completed :)
__Done__. Awaiting review from @dustymabe
> Add blog post on Atomic App 0.3.1 release

- source/layouts/_blog_post.haml
- source/layouts/_social_share.haml
See if this works and looks correct to you, seemed to work ok for me.
> add social sharing buttons to blog posts

- source/blog/2016-01-19-atomic-app-0-4-0.html.md
Fixes a few formatting issues (not showing bash code view) as well the bullet list.
> Fix formatting issues with 4.0 release post

- source/blog/2016-01-25-ADB-1.6-announcement.html.md
First DRAFT
Don't merge yet - giving this a slightly wider visibility
@jzb @navidshaikh
> ADB 1.6 Announcement

- source/blog/2016-02-17-ADB-1-7.html.md
This is an edited version of the ADB 1.7.0 release announcement.  It includes edits and changes from @bexelbie, as well as re-arrranging the text for better flow and deduplication.
However a number of questions remain for @LalatenduMohanty:
1. What is SCCLI?  I find no mention of it in the ADB docs anywhere.  Can you explain this feature?
2. The Changelog for the ADB git repo hasn't been updated.  When will it be?
3. Is my explanation of the benefit of the OpenShift service correct?
> Adb 170 release, revised

- source/blog/2016-02-18-atomic-app-0-4-2.html.md
ping @dustymabe for a quick look-over before posting :) (may add more features towards the end of the day)
> Blog post for Atomic App 0.4.2

- source/layouts/_social.haml
- source/layouts/basic.html.haml
> add feed icon and link

- data/navigation.yml
- source/stylesheets/_application-custom.css.sass
> Add social media and RSS to sidebar

- source/blog/2016-02-22-skopeo-inspect-remote-images.html.md
/cc @rhatdan 
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
> add skopeo post

- data/authors.yml
- source/blog/2016-03-01-project-atomic-gsoc-2016.md
- source/community/gsoc.html.md
@bproffitt please review and publish
> Updated GSOC page, added blog post about participating in GSOC

- source/blog/2016-02-29-new-centos-atomic-host-images-available-for-download.html.md
Edited version of the CentOS Atomic Host blog post.  Ready for @bproffitt
> Jasonbrooks pr feb cah announce

- source/blog/2016-02-29-vagrant-service-manager-0.0.3.html.md
@navidshaikh will do the release on 29 Feb
This draft is believed to be technically complete.  It has been reviewed by @navidshaikh @LalatenduMohanty and @bexelbie
> vagrant-service-manager 0.0.3 release announcement

- source/blog/2016-03-04-dwalsh_selinux_containers.md
New blog post by Dan.  I've already reviewed and edited it.
@bproffitt, this is good to go if @rhatdan is fine with it.  Dan, I changed the title to "Practical SELinux and Containers".  Does that work for you?
> Added draft of Dan's selinux blog post.

- source/blog/2016-03-10-ADB-1-7-1.html.md
ADB 1.7.1 post, including a couple of copy-edits.  @bproffitt this is ready to go and should go out today.
@LalatenduMohanty
> Lalatendu mohanty adb 171

- source/blog/2016-03-16-atomic-app-044-release.md
@cdrage please check.
@bproffitt, if no comments from @cdrage, ready to go.
> Added Atomic App 0.4.4. release announcement.

- source/blog/2016-03-31-atomic-app-0-4-5-release.md
Only a minor release this week!
> Add blog post for Atomic App 0.4.5 release

- data/authors.yml
- source/blog/2016-03-24-developing-with-mesos-marathon-on-atomic-developer-bundle.md
@jberkus @bproffitt I am pretty late in submitting this PR. Can you please suggest if it requires any changes?
> Developing with Mesos-Marathon on ADB

- source/index.html.haml
New new version, without the merge issues.  Replaces PR #288 and #289.
> Atomic registry homepage

- data/authors.yml
- source/blog/2016-04-08-cockpit-kubernetes-volumes-0.101.md
This is about the Cockpit 0.101 release.
> Add blog post for Cockpit and Kubernetes Volumes

- source/blog/2016-04-12-running_OCI.md
mrunalp's blog post on using runc.
> Added first draft of OCI blog post.

- source/docs/nulecule.md
Update this page with more up-to-date information
> Modify Nulecule page

- source/blog/2016-04-25-postgresql-ha-kubernetes.html.md
@bproffitt please review and post
> Added blog post with my video from Kubecon.

- source/blog/2016-04-26-k8s-adb-usage.html.md
Added step by step walk-through to using Kubernetes on
ADB.
This is a formatting-corrected version of @surajssd post.  Ready for @bproffitt
> Using Kubernetes with ADB

- source/blog/2016-04-28-gsoc-projects-accepted.html.md
@bproffitt over to you.  Would be nice to get this out today, since there are more posts coming tommorrow.
> Added blog post about GSOC students.

- source/blog/2016-04-27-App-Development-on-OpenShift-using-ADB.md
This blog post is for app development and deployment on openshift using Atomic Developer bundle.
> Add blog for app development on openshift using ADB

- source/blog/2016-05-13-using-the-atomic-cli-to-scan-vms.html.md
Corrected version of @baude post.
@bproffitt, this is ready to go.
> Baude atomic scan virt

- data/authors.yml
- source/blog/2016-05-19-introducing_commissaire.html.md
@bproffitt this is ready to go.  Hopefully you can push it Thursday.  Thanks!
> Added Introducting Commissaire blog post.

- source/docs/introduction.md
Systemd was discussed twice; this made the page confusing to read.
> Remove duplicate mention of systemd

- source/blog/2016-05-24-atomic-app-0-5-2-release.html.md
Fixed multiple formatting issues, replaces PR #318 
@bproffitt this is ready to go.
> Cdrage 0 5 2 atomicapp release

- source/blog/2016-06-07-micro-cluster-part-1.html.md
@bproffitt please look over for editorial, then publish.  Target it tommorrow.
> Added blog post about building a tiny cluster.

- source/blog/2016-06-10-origin-on-fedora.html.md
@bproffitt please copy-edit.  Target publicaiton is tommorrow.   Thanks!
> added blog about origin on FAH from FAD

- source/blog/2016-05-31-atomic-app-0-6-0-release.html.md
- source/blog/2016-06-15-atomic-app-0-6-0-release.html.md
@bproffitt file modified and ready for publication as soon as you can.
> Cdrage 0 6 0 atomic app release

- source/blog/2016-07-06-commissaire_video_2.html.md
Video blog post.
Should be ready to go, if so, please push tommorrow.
> Added video blog post from Commissaire folks.

- source/blog/2016-07-11-docker-selinux-flag.html.md
@bproffitt please review.  Target for publication is Monday.
> Added Dan Walsh post about selinux-enabled flag.

- source/docs/introduction.md
- source/index.html.haml
Modified text from @cgwalters additions.  Replaced Kubernetes with LDK.  Added mention of Origin upstream.  Added other projects.  Made changes to homepage to suit.
> Cgwalters intro kube

- source/blog/2016-08-16-vagrant-service-manager-1-3-0-release.html.md
Updated the blog as per latest suggestions.
CC @thatdocslady
> Updated vagrant-service-manager 1.3.0 blog

- data/authors.yml
- source/blog/2016-09-09-intro-to-system-containers.md
- source/blog/2016-09-12-intro-to-system-containers.md
> Giuseppe intro system containers

- source/docs/os-updates.md
Mention the fact that it's also `atomic host`, and the deploy command,
a bit more information about remotes and origins, etc.
> docs/os-updates: Various tweaks/modernization

- source/blog/2016-10-25-how-the-container-registries-prevent-information-leakage.html.md
Edited and formatted version.  @bproffitt can you review for copy-editing issues I missed?
> Runcom skopeo docker errors

- source/blog/2016-10-27-deployment-using-ansible.html.md
Modify #371 
@jberkus Can you have a look at this?
> Remove virtualenv from blog post-automation with ansible-playbook

- source/docs/docker_patches.md
Patch has been dropped for the upcoming docker-1.13 (we have built in support in docker to switch default seccomp profile now)
@rhatdan PTAL
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
> docker_patches: seccomp patch dropped

- source/blog/2016-12-09-notice-to-kubernetes-atomic-users.html.md
@jasonbrooks @dustymabe @maxamillion @bproffitt 
Please review!
> First draft of Notice post.

- source/blog/2017-01-09-remote-access-docker-daemon.html.md
> Talking to docker daemon of atomic host

- source/blog/2017-01-20-centos-atomic-jan17.html.md
> Blogged about new CAH release.

- source/docs/gettingstarted.md
I modified the information about the version of Fedora (from 21 to 25).
> Modified the information about the version of Fedora

- source/blog/2017-02-08-crio-runtimes.html.md
@runcom please review so that I can post it tommorrow.
> Added post about CRIO and alternate runtimes from Runcom.

- source/docs/gettingstarted.md
I ran through the getting started guide, updating as needed to make the guide complete-able on current fedora atomic 25. I also added a link at the end to the ansible scripts, which provide for a much fuller-featured cluster.
> various getting started updates

- source/blog/2017-02-17-fedora-layered-image-release.html.md
Signed-off-by: Adam Miller <maxamillion@fedoraproject.org>
> add Fedora Layered Image Release blog post

- source/docs/gettingstarted.md
Taking into consideration that this documentation is the only way to obtain some knowledge regarding Atomic host, is of paramount importance that the approach given to the documentation, will be enlightening.
> Improving the understanding of the functioning of the local registry

- source/blog/2017-02-13-automate-building-atomic-host.html.md
> Automate building atomic host

- source/docs/fedora_atomic_bare_metal_installation.md
This fixes the problem reported here:
https://github.com/projectatomic/atomic-site/pull/410#issuecomment-283237173
> docs: fix fedora boot screen

- source/blog/2017-03-14-fedora-vfad-container-policy.html.md
@dustymabe @maxamillion @jasonbrooks @bproffitt please review. Target publication is tommorrow.
> Created blog about VFAD March 10th.

- source/blog/2017-04-07-contribute-to-atomic-host-doc.html.md
Signed-off-by: Trishna Guha <trishnaguha17@gmail.com>
Fixes #420
> Post for contributing to Atomic host Doc

- source/blog/2017-05-03-minishift-intro.html.md
Hi @jberkus ,
Please review the changes for the blog. I have updated the blog post with all the required changes.
Please let us know if there is any changes still required.
> Introducing minishift - run openshift locally

- source/blog/2017-05-15-single-overlayfs-volume.html.md
@jasonbrooks @bproffitt please check for errors, will publish Monday.
> Added blog post with target date of Monday.

- source/docs/os-updates.md
Hi guys,
Had to search deep to found out how to use package layering behind a corporate proxy.
With this add-on to the documentation i would like to let others know how...
Hope someone would modify rpm-ostree in a next release to use the 'proxy=' line in '/etc/yum.conf' instead.
Kind regards,
Herman Bakker
> Update of os-updates.md describing how to set proxy-settings.

- source/blog/2017-06-06-using-kubeadm-with-cri-o.html.md
@jberkus @rhatdan @bproffitt @mrunalp PTAL
Signed-off-by: Antonio Murdaca <runcom@redhat.com>
> Add "Using kubeadm with CRI-O" blog

- data/authors.yml
- source/blog/2017-06-22-introducing-buildah.html.md
Draft with my revisions per issue.
> Added revised draft of Buildah post.

- source/blog/2017-06-22-introducing-buildah.html.md
Small typo correction.
Changes:  "As we'll seen in a future blog" to "As we'll see in a future blog", dropping the 'n' in seen.
> Fix up small typo, seen to see

- source/index.html.haml
This change overhauls the homepage to reflect all of our current projects. Please review @bproffitt @jzb
> Revamped homepage.

- source/blog/2017-07-12-unprivileged-containers-with-bwrap-oci-and-bubblewrap.md
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
> Blog: "Unprivileged containers with bwrap-oci and bubblewrap"

- source/blog/2017-07-31-fedora-atomic-25-to-26-upgrade.md
In d6ca3fa you undid some of the changes that were requested in the code review. Restoring those changes here.
> restore changes to atomic host upgrade post

- source/blog/2017-08-09-fedora-atomic-august-08.html.md
- fix wording in sentence
- fix link for cloud image checksums
> fixups for 2017-08-09 atomic host release post

- docker.sh
- source/blog/2017-09-12-rpm-ostree-v2017.8-released.html.md
I meant for this to go out along with the two week release last week. As they say, better late than never!
> blog: rpm-ostree v2017.8 released

- source/blog/2017-10-13-ostree-reboot-saga.html.md
@cgwalters @jlebon check this for errors?  Thanks.
> Added blog post about ostree rollback from a bad kernel update.

- source/docs/docker-storage-recommendation.md
Fixes:
* L7: Adding storage to an Atomic hosts -> host
* L41: two options is -> are
* L123: exisiting -> existing
* docker -> Docker
> Fix typos.

- source/blog/2017-11-14-fedora-atomic-27-features.html.md
Please review, comment.
Also,  we're missing several links:
* where will images/ostree for Workstation live?
* where will alternate arch downloads be?
> [WIP] Draft of F27 Atomic release blog post for comments.

- source/blog/2017-11-14-fedora-atomic-26-to-27-upgrade.md
for https://pagure.io/atomic-wg/issue/365
This is a WIP to be published after the first release of f27 atomic host and after the kubernetes migration articles are published. Opening here for now. Will make final changes and fixups next week.
> [WIP] add in 2017-11 blog post for FAH 26->27 upgrade

- source/blog/2017-11-17-installing-etcd-as-a-system-container.md
This is the final, edited version of the "Etcd as system container" blog post.  
To be published Friday, Nov 17.
> Final: Ashcrow system container blog

- source/blog/2017-12-20-project-atomic-docker-hub-namespace-changes.md
- source/blog/2018-01-04-project-atomic-docker-hub-namespace-changes.md
From atomic-wg discussion many weeks ago.
> blog: Project Atomic Docker Hub Namespace Changes

- source/blog/2018-01-16-using-image-registries-with-buildah.md
Signed-off-by: William Henry <whenry@redhat.com>
> Blog tutorial on using Buildah with various image registries

- source/blog/2018-02-06-fedora-atomic-workstation.html.md
I tried to keep the text somewhat accessible even from people less
familiar with Atomic Host/Project Atomic in case folks are "cold-linked"
to the post from somewhere else.
> blog: new post to introduce Fedora Atomic Workstation

- source/docs/fedora-atomic-workstation.md
It turns out that the syntax for links is [title](url), not [url](title).
Fix this mixup throughout the document.
> Make the links work

- source/blog/2018-02-26-reintroduction-podman.html.md
- removed trailing whitespace
- added additional links
- removed some spurious chars that may have been footnotes?
> blog: cleanup reintro podman post

- source/blog/2018-02-28-building-buildah-container-image-for-kubernetes.md
- source/blog/2018-02-28-fedora-atomic-28-feb-18.html.md
Signed-off-by: William Henry @ipbabble <whenry@redhat.com>
> New blog post for building a Buildah container image for Kubernetes

- data/navigation.yml
- source/community/talks.md
- source/index.html.haml
- source/stylesheets/_application-custom.css.sass
> handful of front page changes, talks page

- source/blog/2018-04-05-Buildah-Alpha-version-v0.16.md
Add Buildah Alpha v0.16 Release Announcement to the Project Atomic Blog.  @rhatdan @sanjabonic PTAL and holler if I need to tweak things.
> Add Buildah Alpha v0.16 Release Announcement

- data/authors.yml
- source/docs/quickstart.md
- test-pull.py
Adapting and correcting the python3 pattern (parentheses and string formatting). It's OK!
> Adapting and correcting the python3 pattern 

- source/docs/gettingstarted.md
Not exactly sure what the original intent of the sentence was. This is my best guess.
> Fix wording

- source/blog/2018-05-01-podman-varlink.md
Signed-off-by: baude <bbaude@redhat.com>
> blog for varlink and podman intro

- source/docs/gettingstarted.md
A little detail, but important :)
> Atomic Fedora new release

- source/blog/2018-05-24-podman-userns.md
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
> blog: podman userns

- source/blog/2018-05-24-podman-userns.md
Address some comments I got on the blog post
Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>
> blog: some improvements for the podman&userns post

- source/blog/2018-06-12-Buildah-version-v1.1.html.md
Sanja please review and merge if you see fit.  Buildah v1.1 Release Announcement.
> Buidah v1.1 Release Announcement

- source/blog/2018-02-06-fedora-atomic-workstation.html.md
Someone kindly reported this to me by email.
> blog: fix YouTube link in FAW post

- source/docs/gettingstarted.md
I see a few issues in the command.
- the option `name` is not followed by the `=` sign
- there is no need to create a unit file to ensure the container will always run. Just add `--restart always` option
> update local docker registry

- source/blog/2018-07-18-Buildah-version-v1.2.html.md
Create the Buildah v1.2 Release Announcement
> Create Buildah v1.2 Release Announcement

- source/docs/gettingstarted.md
Add the `etcd` package must be installed.
> update configure etcd

- source/docs/docker-building-images.md
I noted these while studying the documentation. So I figured to quickly make a patch.
> Fix a couple of minor typs

- source/docs/cockpit.md
Hitting this issue on Atomic for CentOS
https://github.com/cockpit-project/cockpit-project.github.io/issues/116
Updating docs to reflect change
> Update Cockpit section to do install
